class CfgArsenal {
	class Weapons {
		#define WEP_OTHER 100
		#define BASE_ARIFLE 600
		#define MOD_GL 150
		#define BASE_MG 1650
		#define BASE_HGUN 150
		#define BASE_LAUNCH 1900
		#define BASE_SRIFLE 1750
		#define BASE_SMG 350
		list[] = {
			{"LMG_03_F",                        __EVAL(BASE_MG)},
			{"LMG_Mk200_F",                     __EVAL(BASE_MG)},
			{"LMG_Zafir_F",                     __EVAL(BASE_MG)},
			{"MMG_01_tan_F",                    __EVAL(BASE_MG)},
			{"MMG_02_black_F",                  __EVAL(BASE_MG)},
			{"MineDetector",                    __EVAL(WEP_OTHER)},
			{"SMG_01_F",                        __EVAL(BASE_SMG)},
			{"SMG_02_F",                        __EVAL(BASE_SMG)},
			{"SMG_05_F",                        __EVAL(BASE_SMG)},
			{"arifle_AK12_GL_F",                __EVAL(BASE_ARIFLE + MOD_GL)},
			{"arifle_AKM_F",                    __EVAL(BASE_ARIFLE)},
			{"arifle_AKS_F",                    __EVAL(BASE_ARIFLE)},
			{"arifle_CTARS_blk_F",              __EVAL(BASE_ARIFLE)},
			{"arifle_CTAR_GL_blk_F",            __EVAL(BASE_ARIFLE + MOD_GL)},
			{"arifle_CTAR_blk_F",               __EVAL(BASE_ARIFLE)},
			{"arifle_Katiba_C_F",               __EVAL(BASE_ARIFLE)},
			{"arifle_Katiba_GL_F",              __EVAL(BASE_ARIFLE + MOD_GL)},
			{"arifle_MXC_Black_F",              __EVAL(BASE_ARIFLE)},
			{"arifle_MXM_Black_F",              __EVAL(BASE_ARIFLE)},
			{"arifle_MX_Black_F",               __EVAL(BASE_ARIFLE)},
			{"arifle_MX_SW_Black_F",            __EVAL(BASE_ARIFLE)},
			{"arifle_MX_khk_F",                 __EVAL(BASE_ARIFLE)},
			{"arifle_Mk20C_F",                  __EVAL(BASE_ARIFLE)},
			{"arifle_Mk20_F",                   __EVAL(BASE_ARIFLE)},
			{"arifle_SDAR_F",                   __EVAL(BASE_ARIFLE)},
			{"arifle_SPAR_01_GL_blk_F",         __EVAL(BASE_ARIFLE + MOD_GL)},
			{"arifle_SPAR_01_blk_F",            __EVAL(BASE_ARIFLE)},
			{"arifle_SPAR_02_blk_F",            __EVAL(BASE_ARIFLE)},
			{"arifle_SPAR_03_blk_F",            __EVAL(BASE_ARIFLE)},
			{"arifle_TRG20_F",                  __EVAL(BASE_ARIFLE)},
			{"arifle_TRG21_F",                  __EVAL(BASE_ARIFLE)},
			{"arifle_TRG21_GL_F",               __EVAL(BASE_ARIFLE + MOD_GL)},
			{"hgun_ACPC2_F",                    __EVAL(BASE_HGUN)},
			{"hgun_P07_F",                      __EVAL(BASE_HGUN)},
			{"hgun_P07_khk_F",                  __EVAL(BASE_HGUN)},
			{"hgun_PDW2000_F",                  __EVAL(BASE_HGUN + 100)},
			{"hgun_Pistol_01_F",                __EVAL(BASE_HGUN)},
			{"hgun_Pistol_Signal_F",            __EVAL(BASE_HGUN)},
			{"hgun_Pistol_heavy_01_F",          __EVAL(BASE_HGUN)},
			{"hgun_Pistol_heavy_02_F",          __EVAL(BASE_HGUN)},
			{"hgun_Pistol_heavy_02_Yorris_F",   __EVAL(BASE_HGUN)},
			{"hgun_Rook40_F",                   __EVAL(BASE_HGUN)},
			{"launch_RPG32_F",                  __EVAL(BASE_LAUNCH)},
			{"launch_RPG32_ghex_F",             __EVAL(BASE_LAUNCH)},
			{"launch_RPG7_F",                   __EVAL(BASE_LAUNCH)},
			{"srifle_DMR_01_F",                 __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_02_camo_F",            __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_03_F",                 __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_03_woodland_F",        __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_04_F",                 __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_05_blk_F",             __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_06_camo_F",            __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_06_camo_khs_F",        __EVAL(BASE_SRIFLE)},
			{"srifle_DMR_07_blk_F",             __EVAL(BASE_SRIFLE)},
			{"srifle_EBR_F",                    __EVAL(BASE_SRIFLE)},
			{"srifle_GM6_F",                    __EVAL(BASE_SRIFLE)},
			{"srifle_LRR_F",                    __EVAL(BASE_SRIFLE)},
			{"srifle_LRR_tna_F",                __EVAL(BASE_SRIFLE)}
		};
	};
	class Magazines {
		#define MAG_OTHER 50
		#define BASE_MAG 50
		#define BASE_GRENRND 100
		#define MOD_SMOKEFLARE -50
		#define BASE_EXPLOS 150
		list[] = {
			{"100Rnd_580x42_Mag_F",                               __EVAL(BASE_MAG)},
			{"100Rnd_580x42_Mag_Tracer_F",                        __EVAL(BASE_MAG)},
			{"100Rnd_65x39_caseless_mag",                         __EVAL(BASE_MAG)},
			{"100Rnd_65x39_caseless_mag_Tracer",                  __EVAL(BASE_MAG)},
			{"10Rnd_127x54_Mag",                                  __EVAL(BASE_MAG)},
			{"10Rnd_338_Mag",                                     __EVAL(BASE_MAG)},
			{"10Rnd_50BW_Mag_F",                                  __EVAL(BASE_MAG)},
			{"10Rnd_762x54_Mag",                                  __EVAL(BASE_MAG)},
			{"10Rnd_93x64_DMR_05_Mag",                            __EVAL(BASE_MAG)},
			{"10Rnd_9x21_Mag",                                    __EVAL(BASE_MAG)},
			{"11Rnd_45ACP_Mag",                                   __EVAL(BASE_MAG)},
			{"130Rnd_338_Mag",                                    __EVAL(BASE_MAG)},
			{"150Rnd_556x45_Drum_Mag_F",                          __EVAL(BASE_MAG)},
			{"150Rnd_556x45_Drum_Mag_Tracer_F",                   __EVAL(BASE_MAG)},
			{"150Rnd_762x54_Box",                                 __EVAL(BASE_MAG)},
			{"150Rnd_762x54_Box_Tracer",                          __EVAL(BASE_MAG)},
			{"150Rnd_93x64_Mag",                                  __EVAL(BASE_MAG)},
			{"16Rnd_9x21_Mag",                                    __EVAL(BASE_MAG)},
			{"16Rnd_9x21_green_Mag",                              __EVAL(BASE_MAG)},
			{"16Rnd_9x21_red_Mag",                                __EVAL(BASE_MAG)},
			{"16Rnd_9x21_yellow_Mag",                             __EVAL(BASE_MAG)},
			{"1Rnd_HE_Grenade_shell",                             __EVAL(BASE_GRENRND)},
			{"1Rnd_SmokeBlue_Grenade_shell",                      __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"1Rnd_SmokeGreen_Grenade_shell",                     __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"1Rnd_SmokeOrange_Grenade_shell",                    __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"1Rnd_SmokePurple_Grenade_shell",                    __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"1Rnd_SmokeRed_Grenade_shell",                       __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"1Rnd_SmokeYellow_Grenade_shell",                    __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"1Rnd_Smoke_Grenade_shell",                          __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"200Rnd_556x45_Box_F",                               __EVAL(BASE_MAG)},
			{"200Rnd_556x45_Box_Red_F",                           __EVAL(BASE_MAG)},
			{"200Rnd_556x45_Box_Tracer_F",                        __EVAL(BASE_MAG)},
			{"200Rnd_556x45_Box_Tracer_Red_F",                    __EVAL(BASE_MAG)},
			{"200Rnd_65x39_cased_Box",                            __EVAL(BASE_MAG)},
			{"200Rnd_65x39_cased_Box_Tracer",                     __EVAL(BASE_MAG)},
			{"20Rnd_556x45_UW_mag",                               __EVAL(BASE_MAG)},
			{"20Rnd_650x39_Cased_Mag_F",                          __EVAL(BASE_MAG)},
			{"20Rnd_762x51_Mag",                                  __EVAL(BASE_MAG)},
			{"30Rnd_45ACP_Mag_SMG_01",                            __EVAL(BASE_MAG)},
			{"30Rnd_45ACP_Mag_SMG_01_Tracer_Green",               __EVAL(BASE_MAG)},
			{"30Rnd_45ACP_Mag_SMG_01_Tracer_Red",                 __EVAL(BASE_MAG)},
			{"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",              __EVAL(BASE_MAG)},
			{"30Rnd_545x39_Mag_F",                                __EVAL(BASE_MAG)},
			{"30Rnd_545x39_Mag_Green_F",                          __EVAL(BASE_MAG)},
			{"30Rnd_545x39_Mag_Tracer_F",                         __EVAL(BASE_MAG)},
			{"30Rnd_545x39_Mag_Tracer_Green_F",                   __EVAL(BASE_MAG)},
			{"30Rnd_556x45_Stanag",                               __EVAL(BASE_MAG)},
			{"30Rnd_556x45_Stanag_Tracer_Green",                  __EVAL(BASE_MAG)},
			{"30Rnd_556x45_Stanag_Tracer_Red",                    __EVAL(BASE_MAG)},
			{"30Rnd_556x45_Stanag_Tracer_Yellow",                 __EVAL(BASE_MAG)},
			{"30Rnd_556x45_Stanag_green",                         __EVAL(BASE_MAG)},
			{"30Rnd_556x45_Stanag_red",                           __EVAL(BASE_MAG)},
			{"30Rnd_580x42_Mag_F",                                __EVAL(BASE_MAG)},
			{"30Rnd_580x42_Mag_Tracer_F",                         __EVAL(BASE_MAG)},
			{"30Rnd_65x39_caseless_green",                        __EVAL(BASE_MAG)},
			{"30Rnd_65x39_caseless_green_mag_Tracer",             __EVAL(BASE_MAG)},
			{"30Rnd_65x39_caseless_mag",                          __EVAL(BASE_MAG)},
			{"30Rnd_65x39_caseless_mag_Tracer",                   __EVAL(BASE_MAG)},
			{"30Rnd_762x39_Mag_F",                                __EVAL(BASE_MAG)},
			{"30Rnd_762x39_Mag_Green_F",                          __EVAL(BASE_MAG)},
			{"30Rnd_762x39_Mag_Tracer_F",                         __EVAL(BASE_MAG)},
			{"30Rnd_762x39_Mag_Tracer_Green_F",                   __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Green_Mag",                              __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Mag",                                    __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Mag_SMG_02",                             __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Mag_SMG_02_Tracer_Green",                __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Mag_SMG_02_Tracer_Red",                  __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Mag_SMG_02_Tracer_Yellow",               __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Red_Mag",                                __EVAL(BASE_MAG)},
			{"30Rnd_9x21_Yellow_Mag",                             __EVAL(BASE_MAG)},
			{"5Rnd_127x108_APDS_Mag",                             __EVAL(BASE_MAG)},
			{"5Rnd_127x108_Mag",                                  __EVAL(BASE_MAG)},
			{"6Rnd_45ACP_Cylinder",                               __EVAL(BASE_MAG)},
			{"6Rnd_GreenSignal_F",                                __EVAL(BASE_MAG)},
			{"6Rnd_RedSignal_F",                                  __EVAL(BASE_MAG)},
			{"7Rnd_408_Mag",                                      __EVAL(BASE_MAG)},
			{"9Rnd_45ACP_Mag",                                    __EVAL(BASE_MAG)},
			{"ACE_100Rnd_65x39_caseless_mag_Tracer_Dim",          __EVAL(BASE_MAG)},
			{"ACE_10Rnd_338_300gr_HPBT_Mag",                      __EVAL(BASE_MAG)},
			{"ACE_10Rnd_338_API526_Mag",                          __EVAL(BASE_MAG)},
			{"ACE_10Rnd_762x54_Tracer_mag",                       __EVAL(BASE_MAG)},
			{"ACE_200Rnd_65x39_cased_Box_Tracer_Dim",             __EVAL(BASE_MAG)},
			{"ACE_20Rnd_65_Creedmor_mag",                         __EVAL(BASE_MAG)},
			{"ACE_20Rnd_65x47_Scenar_mag",                        __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_M118LR_Mag",                       __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_M993_AP_Mag",                      __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_Mag_SD",                           __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_Mag_Tracer",                       __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_Mag_Tracer_Dim",                   __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_Mk316_Mod_0_Mag",                  __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x51_Mk319_Mod_0_Mag",                  __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag",            __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x67_Mk248_Mod_0_Mag",                  __EVAL(BASE_MAG)},
			{"ACE_20Rnd_762x67_Mk248_Mod_1_Mag",                  __EVAL(BASE_MAG)},
			{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",               __EVAL(BASE_MAG)},
			{"ACE_30Rnd_556x45_Stanag_Mk262_mag",                 __EVAL(BASE_MAG)},
			{"ACE_30Rnd_556x45_Stanag_Mk318_mag",                 __EVAL(BASE_MAG)},
			{"ACE_30Rnd_556x45_Stanag_Tracer_Dim",                __EVAL(BASE_MAG)},
			{"ACE_30Rnd_65_Creedmor_mag",                         __EVAL(BASE_MAG)},
			{"ACE_30Rnd_65x39_caseless_green_mag_Tracer_Dim",     __EVAL(BASE_MAG)},
			{"ACE_30Rnd_65x39_caseless_mag_Tracer_Dim",           __EVAL(BASE_MAG)},
			{"ACE_30Rnd_65x47_Scenar_mag",                        __EVAL(BASE_MAG)},
			{"ACE_5Rnd_127x99_AMAX_Mag",                          __EVAL(BASE_MAG)},
			{"ACE_5Rnd_127x99_API_Mag",                           __EVAL(BASE_MAG)},
			{"ACE_5Rnd_127x99_Mag",                               __EVAL(BASE_MAG)},
			{"ACE_7Rnd_408_305gr_Mag",                            __EVAL(BASE_MAG)},
			{"ACE_Chemlight_HiOrange",                            __EVAL(MAG_OTHER)},
			{"ACE_Chemlight_HiRed",                               __EVAL(MAG_OTHER)},
			{"ACE_Chemlight_HiWhite",                             __EVAL(MAG_OTHER)},
			{"ACE_Chemlight_HiYellow",                            __EVAL(MAG_OTHER)},
			{"ACE_Chemlight_IR",                                  __EVAL(MAG_OTHER)},
			{"ACE_Chemlight_Orange",                              __EVAL(MAG_OTHER)},
			{"ACE_Chemlight_White",                               __EVAL(MAG_OTHER)},
			{"ACE_HandFlare_Green",                               __EVAL(MAG_OTHER)},
			{"ACE_HandFlare_Red",                                 __EVAL(MAG_OTHER)},
			{"ACE_HandFlare_White",                               __EVAL(MAG_OTHER)},
			{"ACE_HandFlare_Yellow",                              __EVAL(MAG_OTHER)},
			{"ACE_HuntIR_M203",                                   __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"ACE_M14",                                           __EVAL(BASE_EXPLOS)},
			{"ACE_M84",                                           __EVAL(BASE_EXPLOS)},
			{"APERSBoundingMine_Range_Mag",                       __EVAL(BASE_EXPLOS)},
			{"APERSMineDispenser_Mag",                            __EVAL(BASE_EXPLOS)},
			{"APERSMine_Range_Mag",                               __EVAL(BASE_EXPLOS)},
			{"APERSTripMine_Wire_Mag",                            __EVAL(BASE_EXPLOS)},
			{"ATMine_Range_Mag",                                  __EVAL(BASE_EXPLOS)},
			{"B_IR_Grenade",                                      __EVAL(MAG_OTHER)},
			{"Chemlight_blue",                                    __EVAL(MAG_OTHER)},
			{"Chemlight_green",                                   __EVAL(MAG_OTHER)},
			{"Chemlight_red",                                     __EVAL(MAG_OTHER)},
			{"Chemlight_yellow",                                  __EVAL(MAG_OTHER)},
			{"ClaymoreDirectionalMine_Remote_Mag",                __EVAL(BASE_EXPLOS)},
			{"DemoCharge_Remote_Mag",                             __EVAL(BASE_EXPLOS)},
			{"HandGrenade",                                       __EVAL(BASE_EXPLOS)},
			{"IEDLandBig_Remote_Mag",                             __EVAL(BASE_EXPLOS)},
			{"IEDLandSmall_Remote_Mag",                           __EVAL(BASE_EXPLOS)},
			{"IEDUrbanBig_Remote_Mag",                            __EVAL(BASE_EXPLOS)},
			{"IEDUrbanSmall_Remote_Mag",                          __EVAL(BASE_EXPLOS)},
			{"Laserbatteries",                                    __EVAL(MAG_OTHER)},
			{"MiniGrenade",                                       __EVAL(BASE_EXPLOS)},
			{"RPG32_F",                                           __EVAL(BASE_EXPLOS)},
			{"RPG32_HE_F",                                        __EVAL(BASE_EXPLOS)},
			{"RPG7_F",                                            __EVAL(BASE_EXPLOS)},
			{"SLAMDirectionalMine_Wire_Mag",                      __EVAL(BASE_EXPLOS)},
			{"SatchelCharge_Remote_Mag",                          __EVAL(BASE_EXPLOS)},
			{"SmokeShell",                                        __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"SmokeShellBlue",                                    __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"SmokeShellGreen",                                   __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"SmokeShellOrange",                                  __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"SmokeShellPurple",                                  __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"SmokeShellRed",                                     __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"SmokeShellYellow",                                  __EVAL(BASE_GRENRND + MOD_SMOKEFLARE - 30)},
			{"TrainingMine_Mag",                                  __EVAL(MAG_OTHER)},
			{"UGL_FlareCIR_F",                                    __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"UGL_FlareGreen_F",                                  __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"UGL_FlareRed_F",                                    __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"UGL_FlareWhite_F",                                  __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)},
			{"UGL_FlareYellow_F",                                 __EVAL(BASE_GRENRND + MOD_SMOKEFLARE)}
		};
	};
	class Backpacks {
		#define BAK_OTHER 250
		#define BASE_PACK 500
		list[] = {
			{"ACE_TacticalLadder_Pack",                __EVAL(BAK_OTHER)},
			{"B_AssaultPack_blk",                      __EVAL(BASE_PACK)},
			{"B_AssaultPack_rgr",                      __EVAL(BASE_PACK)},
			{"B_AssaultPack_tna_F",                    __EVAL(BASE_PACK)},
			{"B_Bergen_dgtl_F",                        __EVAL(BASE_PACK)},
			{"B_Bergen_tna_F",                         __EVAL(BASE_PACK)},
			{"B_Carryall_oli",                         __EVAL(BASE_PACK)},
			{"B_FieldPack_blk",                        __EVAL(BASE_PACK)},
			{"B_FieldPack_oli",                        __EVAL(BASE_PACK)},
			{"B_Kitbag_rgr",                           __EVAL(BASE_PACK)},
			{"B_LegStrapBag_black_F",                  __EVAL(BASE_PACK)},
			{"B_LegStrapBag_olive_F",                  __EVAL(BASE_PACK)},
			{"B_Messenger_Black_F",                    __EVAL(BASE_PACK)},
			{"B_Messenger_Olive_F",                    __EVAL(BASE_PACK)},
			{"B_Parachute",                            __EVAL(BAK_OTHER)},
			{"B_Patrol_Respawn_bag_F",                 __EVAL(BAK_OTHER)},
			{"B_Respawn_Sleeping_bag_F",               __EVAL(BAK_OTHER)},
			{"B_Respawn_Sleeping_bag_blue_F",          __EVAL(BAK_OTHER)},
			{"B_Respawn_Sleeping_bag_brown_F",         __EVAL(BAK_OTHER)},
			{"B_Respawn_TentA_F",                      __EVAL(BAK_OTHER)},
			{"B_Respawn_TentDome_F",                   __EVAL(BAK_OTHER)},
			{"B_Static_Designator_01_weapon_F",        __EVAL(BASE_PACK)},
			{"B_TacticalPack_blk",                     __EVAL(BASE_PACK)},
			{"B_TacticalPack_oli",                     __EVAL(BASE_PACK)},
			{"B_UAV_01_backpack_F",                    __EVAL(BASE_PACK)},
			{"B_UAV_06_backpack_F",                    __EVAL(BASE_PACK)},
			{"B_UAV_06_medical_backpack_F",            __EVAL(BASE_PACK)},
			{"B_ViperHarness_blk_F",                   __EVAL(BASE_PACK)},
			{"B_ViperHarness_oli_F",                   __EVAL(BASE_PACK)},
			{"B_ViperLightHarness_blk_F",              __EVAL(BASE_PACK)},
			{"B_ViperLightHarness_oli_F",              __EVAL(BASE_PACK)},
			{"ace_gunbag",                             __EVAL(BASE_PACK)},
			{"ace_gunbag_Tan",                         __EVAL(BASE_PACK)},
			{"tf_anarc210",                            __EVAL(BASE_PACK)}
		};
	};
	class Items {
		#define ITEM_OTHER 50
		list[] = {
			{"ACE_ATragMX",                        __EVAL(ITEM_OTHER)},
			{"ACE_Altimeter",                      __EVAL(ITEM_OTHER)},
			{"ACE_CableTie",                       __EVAL(ITEM_OTHER)},
			{"ACE_Cellphone",                      __EVAL(ITEM_OTHER)},
			{"ACE_Chemlight_Shield",               __EVAL(ITEM_OTHER)},
			{"ACE_Clacker",                        __EVAL(ITEM_OTHER)},
			{"ACE_DAGR",                           __EVAL(ITEM_OTHER)},
			{"ACE_DeadManSwitch",                  __EVAL(ITEM_OTHER)},
			{"ACE_DefusalKit",                     __EVAL(ITEM_OTHER)},
			{"ACE_EarPlugs",                       __EVAL(ITEM_OTHER)},
			{"ACE_EntrenchingTool",                __EVAL(ITEM_OTHER)},
			{"ACE_Flashlight_KSF1",                __EVAL(ITEM_OTHER)},
			{"ACE_Flashlight_MX991",               __EVAL(ITEM_OTHER)},
			{"ACE_Flashlight_XL50",                __EVAL(ITEM_OTHER)},
			{"ACE_HuntIR_monitor",                 __EVAL(ITEM_OTHER)},
			{"ACE_IR_Strobe_Item",                 __EVAL(ITEM_OTHER)},
			{"ACE_Kestrel4500",                    __EVAL(ITEM_OTHER)},
			{"ACE_M26_Clacker",                    __EVAL(ITEM_OTHER)},
			{"ACE_MX2A",                           __EVAL(ITEM_OTHER)},
			{"ACE_MapTools",                       __EVAL(ITEM_OTHER)},
			{"ACE_NVG_Gen1",                       __EVAL(ITEM_OTHER)},
			{"ACE_NVG_Gen2",                       __EVAL(ITEM_OTHER)},
			{"ACE_NVG_Gen4",                       __EVAL(ITEM_OTHER)},
			{"ACE_NVG_Wide",                       __EVAL(ITEM_OTHER)},
			{"ACE_RangeCard",                      __EVAL(ITEM_OTHER)},
			{"ACE_RangeTable_82mm",                __EVAL(ITEM_OTHER)},
			{"ACE_Sandbag_empty",                  __EVAL(ITEM_OTHER)},
			{"ACE_SpottingScope",                  __EVAL(ITEM_OTHER)},
			{"ACE_SpraypaintBlack",                __EVAL(ITEM_OTHER)},
			{"ACE_SpraypaintBlue",                 __EVAL(ITEM_OTHER)},
			{"ACE_SpraypaintGreen",                __EVAL(ITEM_OTHER)},
			{"ACE_SpraypaintRed",                  __EVAL(ITEM_OTHER)},
			{"ACE_Tripod",                         __EVAL(ITEM_OTHER)},
			{"ACE_UAVBattery",                     __EVAL(ITEM_OTHER)},
			{"ACE_Vector",                         __EVAL(ITEM_OTHER)},
			{"ACE_VectorDay",                      __EVAL(ITEM_OTHER)},
			{"ACE_Yardage450",                     __EVAL(ITEM_OTHER)},
			{"ACE_acc_pointer_green",              __EVAL(ITEM_OTHER)},
			{"ACE_adenosine",                      __EVAL(ITEM_OTHER)},
			{"ACE_atropine",                       __EVAL(ITEM_OTHER)},
			{"ACE_bloodIV",                        __EVAL(ITEM_OTHER)},
			{"ACE_bloodIV_250",                    __EVAL(ITEM_OTHER)},
			{"ACE_bloodIV_500",                    __EVAL(ITEM_OTHER)},
			{"ACE_bodyBag",                        __EVAL(ITEM_OTHER)},
			{"ACE_elasticBandage",                 __EVAL(ITEM_OTHER)},
			{"ACE_epinephrine",                    __EVAL(ITEM_OTHER)},
			{"ACE_fieldDressing",                  __EVAL(ITEM_OTHER)},
			{"ACE_key_lockpick",                   __EVAL(ITEM_OTHER)},
			{"ACE_microDAGR",                      __EVAL(ITEM_OTHER)},
			{"ACE_morphine",                       __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_338",                __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_93mmg",              __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_B",                  __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_H",                  __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_L",                  __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_smg_01",             __EVAL(ITEM_OTHER)},
			{"ACE_muzzle_mzls_smg_02",             __EVAL(ITEM_OTHER)},
			{"ACE_optic_Arco_2D",                  __EVAL(ITEM_OTHER)},
			{"ACE_optic_Arco_PIP",                 __EVAL(ITEM_OTHER)},
			{"ACE_optic_Hamr_2D",                  __EVAL(ITEM_OTHER)},
			{"ACE_optic_Hamr_PIP",                 __EVAL(ITEM_OTHER)},
			{"ACE_optic_LRPS_2D",                  __EVAL(ITEM_OTHER)},
			{"ACE_optic_LRPS_PIP",                 __EVAL(ITEM_OTHER)},
			{"ACE_optic_MRCO_2D",                  __EVAL(ITEM_OTHER)},
			{"ACE_optic_SOS_2D",                   __EVAL(ITEM_OTHER)},
			{"ACE_optic_SOS_PIP",                  __EVAL(ITEM_OTHER)},
			{"ACE_packingBandage",                 __EVAL(ITEM_OTHER)},
			{"ACE_personalAidKit",                 __EVAL(ITEM_OTHER)},
			{"ACE_plasmaIV",                       __EVAL(ITEM_OTHER)},
			{"ACE_plasmaIV_250",                   __EVAL(ITEM_OTHER)},
			{"ACE_plasmaIV_500",                   __EVAL(ITEM_OTHER)},
			{"ACE_quikclot",                       __EVAL(ITEM_OTHER)},
			{"ACE_salineIV",                       __EVAL(ITEM_OTHER)},
			{"ACE_salineIV_250",                   __EVAL(ITEM_OTHER)},
			{"ACE_salineIV_500",                   __EVAL(ITEM_OTHER)},
			{"ACE_surgicalKit",                    __EVAL(ITEM_OTHER)},
			{"ACE_tourniquet",                     __EVAL(ITEM_OTHER)},
			{"ACE_wirecutter",                     __EVAL(ITEM_OTHER)},
			{"B_UavTerminal",                      __EVAL(ITEM_OTHER)},
			{"Binocular",                          __EVAL(ITEM_OTHER)},
			{"G_Aviator",                          __EVAL(ITEM_OTHER)},
			{"G_B_Diving",                         __EVAL(ITEM_OTHER)},
			{"G_Balaclava_TI_G_blk_F",             __EVAL(ITEM_OTHER)},
			{"G_Balaclava_TI_G_tna_F",             __EVAL(ITEM_OTHER)},
			{"G_Balaclava_TI_blk_F",               __EVAL(ITEM_OTHER)},
			{"G_Balaclava_TI_tna_F",               __EVAL(ITEM_OTHER)},
			{"G_Balaclava_blk",                    __EVAL(ITEM_OTHER)},
			{"G_Balaclava_combat",                 __EVAL(ITEM_OTHER)},
			{"G_Balaclava_lowprofile",             __EVAL(ITEM_OTHER)},
			{"G_Balaclava_oli",                    __EVAL(ITEM_OTHER)},
			{"G_Bandanna_aviator",                 __EVAL(ITEM_OTHER)},
			{"G_Bandanna_beast",                   __EVAL(ITEM_OTHER)},
			{"G_Bandanna_blk",                     __EVAL(ITEM_OTHER)},
			{"G_Bandanna_oli",                     __EVAL(ITEM_OTHER)},
			{"G_Bandanna_shades",                  __EVAL(ITEM_OTHER)},
			{"G_Combat",                           __EVAL(ITEM_OTHER)},
			{"G_Combat_Goggles_tna_F",             __EVAL(ITEM_OTHER)},
			{"G_EyeProtectors_Earpiece_F",         __EVAL(ITEM_OTHER)},
			{"G_EyeProtectors_F",                  __EVAL(ITEM_OTHER)},
			{"G_Lowprofile",                       __EVAL(ITEM_OTHER)},
			{"G_Respirator_blue_F",                __EVAL(ITEM_OTHER)},
			{"G_Respirator_white_F",               __EVAL(ITEM_OTHER)},
			{"G_Respirator_yellow_F",              __EVAL(ITEM_OTHER)},
			{"G_Shades_Black",                     __EVAL(ITEM_OTHER)},
			{"G_Spectacles",                       __EVAL(ITEM_OTHER)},
			{"G_Spectacles_Tinted",                __EVAL(ITEM_OTHER)},
			{"G_Squares",                          __EVAL(ITEM_OTHER)},
			{"G_Squares_Tinted",                   __EVAL(ITEM_OTHER)},
			{"G_Tactical_Black",                   __EVAL(ITEM_OTHER)},
			{"G_Tactical_Clear",                   __EVAL(ITEM_OTHER)},
			{"G_WirelessEarpiece_F",               __EVAL(ITEM_OTHER)},
			{"H_Bandanna_camo",                    __EVAL(ITEM_OTHER)},
			{"H_Bandanna_gry",                     __EVAL(ITEM_OTHER)},
			{"H_Bandanna_khk_hs",                  __EVAL(ITEM_OTHER)},
			{"H_Beret_02",                         __EVAL(ITEM_OTHER)},
			{"H_Beret_Colonel",                    __EVAL(ITEM_OTHER)},
			{"H_Beret_blk",                        __EVAL(ITEM_OTHER)},
			{"H_Booniehat_oli",                    __EVAL(ITEM_OTHER)},
			{"H_Booniehat_tna_F",                  __EVAL(ITEM_OTHER)},
			{"H_Cap_blk",                          __EVAL(ITEM_OTHER)},
			{"H_Cap_grn",                          __EVAL(ITEM_OTHER)},
			{"H_Cap_oli",                          __EVAL(ITEM_OTHER)},
			{"H_Cap_oli_hs",                       __EVAL(ITEM_OTHER)},
			{"H_CrewHelmetHeli_B",                 __EVAL(ITEM_OTHER)},
			{"H_EarProtectors_black_F",            __EVAL(ITEM_OTHER)},
			{"H_Hat_Safari_olive_F",               __EVAL(ITEM_OTHER)},
			{"H_Hat_camo",                         __EVAL(ITEM_OTHER)},
			{"H_HeadBandage_bloody_F",             __EVAL(ITEM_OTHER)},
			{"H_HeadBandage_clean_F",              __EVAL(ITEM_OTHER)},
			{"H_HeadBandage_stained_F",            __EVAL(ITEM_OTHER)},
			{"H_HeadSet_black_F",                  __EVAL(ITEM_OTHER)},
			{"H_HelmetB_Enh_tna_F",                __EVAL(ITEM_OTHER)},
			{"H_HelmetB_Light_tna_F",              __EVAL(ITEM_OTHER)},
			{"H_HelmetB_black",                    __EVAL(ITEM_OTHER)},
			{"H_HelmetB_camo",                     __EVAL(ITEM_OTHER)},
			{"H_HelmetB_grass",                    __EVAL(ITEM_OTHER)},
			{"H_HelmetB_light_black",              __EVAL(ITEM_OTHER)},
			{"H_HelmetB_light_grass",              __EVAL(ITEM_OTHER)},
			{"H_HelmetB_tna_F",                    __EVAL(ITEM_OTHER)},
			{"H_HelmetCrew_B",                     __EVAL(ITEM_OTHER)},
			{"H_HelmetIA",                         __EVAL(ITEM_OTHER)},
			{"H_HelmetSpecB_blk",                  __EVAL(ITEM_OTHER)},
			{"H_HelmetSpecB_paint1",               __EVAL(ITEM_OTHER)},
			{"H_MilCap_gry",                       __EVAL(ITEM_OTHER)},
			{"H_MilCap_tna_F",                     __EVAL(ITEM_OTHER)},
			{"H_PASGT_basic_olive_F",              __EVAL(ITEM_OTHER)},
			{"H_PilotHelmetFighter_B",             __EVAL(ITEM_OTHER)},
			{"H_PilotHelmetHeli_B",                __EVAL(ITEM_OTHER)},
			{"H_Shemag_olive",                     __EVAL(ITEM_OTHER)},
			{"H_Shemag_olive_hs",                  __EVAL(ITEM_OTHER)},
			{"H_Watchcap_blk",                     __EVAL(ITEM_OTHER)},
			{"H_Watchcap_camo",                    __EVAL(ITEM_OTHER)},
			{"H_WirelessEarpiece_F",               __EVAL(ITEM_OTHER)},
			{"ItemCompass",                        __EVAL(ITEM_OTHER)},
			{"ItemGPS",                            __EVAL(ITEM_OTHER)},
			{"ItemMap",                            __EVAL(ITEM_OTHER)},
			{"ItemRadio",                          __EVAL(ITEM_OTHER)},
			{"ItemWatch",                          __EVAL(ITEM_OTHER)},
			{"Laserdesignator",                    __EVAL(ITEM_OTHER)},
			{"Laserdesignator_01_khk_F",           __EVAL(ITEM_OTHER)},
			{"Laserdesignator_02",                 __EVAL(ITEM_OTHER)},
			{"Laserdesignator_02_ghex_F",          __EVAL(ITEM_OTHER)},
			{"Laserdesignator_03",                 __EVAL(ITEM_OTHER)},
			{"NVGoggles",                          __EVAL(ITEM_OTHER)},
			{"NVGogglesB_blk_F",                   __EVAL(ITEM_OTHER)},
			{"NVGogglesB_grn_F",                   __EVAL(ITEM_OTHER)},
			{"NVGogglesB_gry_F",                   __EVAL(ITEM_OTHER)},
			{"NVGoggles_INDEP",                    __EVAL(ITEM_OTHER)},
			{"NVGoggles_OPFOR",                    __EVAL(ITEM_OTHER)},
			{"NVGoggles_tna_F",                    __EVAL(ITEM_OTHER)},
			{"O_NVGoggles_ghex_F",                 __EVAL(ITEM_OTHER)},
			{"O_NVGoggles_hex_F",                  __EVAL(ITEM_OTHER)},
			{"O_NVGoggles_urb_F",                  __EVAL(ITEM_OTHER)},
			{"Rangefinder",                        __EVAL(ITEM_OTHER)},
			{"ToolKit",                            __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_1",                         __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_2",                         __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_3",                         __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_Soldier_2_F",               __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_Soldier_3_F",               __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_Soldier_F",                 __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_Soldier_urb_1_F",           __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_Soldier_urb_2_F",           __EVAL(ITEM_OTHER)},
			{"U_B_CTRG_Soldier_urb_3_F",           __EVAL(ITEM_OTHER)},
			{"U_B_CombatUniform_mcam",             __EVAL(ITEM_OTHER)},
			{"U_B_CombatUniform_mcam_tshirt",      __EVAL(ITEM_OTHER)},
			{"U_B_CombatUniform_mcam_worn",        __EVAL(ITEM_OTHER)},
			{"U_B_FullGhillie_ard",                __EVAL(ITEM_OTHER)},
			{"U_B_FullGhillie_lsh",                __EVAL(ITEM_OTHER)},
			{"U_B_FullGhillie_sard",               __EVAL(ITEM_OTHER)},
			{"U_B_GhillieSuit",                    __EVAL(ITEM_OTHER)},
			{"U_B_HeliPilotCoveralls",             __EVAL(ITEM_OTHER)},
			{"U_B_PilotCoveralls",                 __EVAL(ITEM_OTHER)},
			{"U_B_T_FullGhillie_tna_F",            __EVAL(ITEM_OTHER)},
			{"U_B_T_Sniper_F",                     __EVAL(ITEM_OTHER)},
			{"U_B_T_Soldier_AR_F",                 __EVAL(ITEM_OTHER)},
			{"U_B_T_Soldier_F",                    __EVAL(ITEM_OTHER)},
			{"U_B_T_Soldier_SL_F",                 __EVAL(ITEM_OTHER)},
			{"U_B_Wetsuit",                        __EVAL(ITEM_OTHER)},
			{"U_B_survival_uniform",               __EVAL(ITEM_OTHER)},
			{"U_C_IDAP_Man_cargo_F",               __EVAL(ITEM_OTHER)},
			{"U_I_C_Soldier_Para_1_F",             __EVAL(ITEM_OTHER)},
			{"U_I_C_Soldier_Para_2_F",             __EVAL(ITEM_OTHER)},
			{"U_I_C_Soldier_Para_3_F",             __EVAL(ITEM_OTHER)},
			{"U_I_C_Soldier_Para_4_F",             __EVAL(ITEM_OTHER)},
			{"U_I_C_Soldier_Para_5_F",             __EVAL(ITEM_OTHER)},
			{"U_I_G_Story_Protagonist_F",          __EVAL(ITEM_OTHER)},
			{"U_I_G_resistanceLeader_F",           __EVAL(ITEM_OTHER)},
			{"U_Rangemaster",                      __EVAL(ITEM_OTHER)},
			{"V_BandollierB_blk",                  __EVAL(ITEM_OTHER)},
			{"V_BandollierB_oli",                  __EVAL(ITEM_OTHER)},
			{"V_BandollierB_rgr",                  __EVAL(ITEM_OTHER)},
			{"V_Chestrig_blk",                     __EVAL(ITEM_OTHER)},
			{"V_Chestrig_oli",                     __EVAL(ITEM_OTHER)},
			{"V_Chestrig_rgr",                     __EVAL(ITEM_OTHER)},
			{"V_EOD_olive_F",                      __EVAL(ITEM_OTHER)},
			{"V_I_G_resistanceLeader_F",           __EVAL(ITEM_OTHER)},
			{"V_LegStrapBag_black_F",              __EVAL(ITEM_OTHER)},
			{"V_LegStrapBag_olive_F",              __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier1_blk",                __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier1_rgr",                __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier1_rgr_noflag_F",       __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier1_tna_F",              __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier2_blk",                __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier2_rgr",                __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier2_rgr_noflag_F",       __EVAL(ITEM_OTHER)},
			{"V_PlateCarrier2_tna_F",              __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierGL_blk",               __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierGL_rgr",               __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierGL_tna_F",             __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierH_CTRG",               __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierIA1_dgtl",             __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierIA2_dgtl",             __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierIAGL_dgtl",            __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierIAGL_oli",             __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierL_CTRG",               __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierSpec_blk",             __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierSpec_rgr",             __EVAL(ITEM_OTHER)},
			{"V_PlateCarrierSpec_tna_F",           __EVAL(ITEM_OTHER)},
			{"V_Pocketed_black_F",                 __EVAL(ITEM_OTHER)},
			{"V_Pocketed_olive_F",                 __EVAL(ITEM_OTHER)},
			{"V_Rangemaster_belt",                 __EVAL(ITEM_OTHER)},
			{"V_RebreatherB",                      __EVAL(ITEM_OTHER)},
			{"V_TacChestrig_grn_F",                __EVAL(ITEM_OTHER)},
			{"V_TacChestrig_oli_F",                __EVAL(ITEM_OTHER)},
			{"V_TacVestIR_blk",                    __EVAL(ITEM_OTHER)},
			{"V_TacVest_blk",                      __EVAL(ITEM_OTHER)},
			{"V_TacVest_camo",                     __EVAL(ITEM_OTHER)},
			{"V_TacVest_oli",                      __EVAL(ITEM_OTHER)},
			{"acc_flashlight",                     __EVAL(ITEM_OTHER)},
			{"acc_flashlight_pistol",              __EVAL(ITEM_OTHER)},
			{"acc_flashlight_smg_01",              __EVAL(ITEM_OTHER)},
			{"acc_pointer_IR",                     __EVAL(ITEM_OTHER)},
			{"bipod_01_F_blk",                     __EVAL(ITEM_OTHER)},
			{"bipod_01_F_khk",                     __EVAL(ITEM_OTHER)},
			{"bipod_01_F_mtp",                     __EVAL(ITEM_OTHER)},
			{"bipod_01_F_snd",                     __EVAL(ITEM_OTHER)},
			{"bipod_02_F_blk",                     __EVAL(ITEM_OTHER)},
			{"bipod_02_F_hex",                     __EVAL(ITEM_OTHER)},
			{"bipod_02_F_tan",                     __EVAL(ITEM_OTHER)},
			{"bipod_03_F_blk",                     __EVAL(ITEM_OTHER)},
			{"bipod_03_F_oli",                     __EVAL(ITEM_OTHER)},
			{"muzzle_snds_338_black",              __EVAL(ITEM_OTHER)},
			{"muzzle_snds_338_green",              __EVAL(ITEM_OTHER)},
			{"muzzle_snds_338_sand",               __EVAL(ITEM_OTHER)},
			{"muzzle_snds_58_blk_F",               __EVAL(ITEM_OTHER)},
			{"muzzle_snds_58_ghex_F",              __EVAL(ITEM_OTHER)},
			{"muzzle_snds_58_hex_F",               __EVAL(ITEM_OTHER)},
			{"muzzle_snds_65_TI_blk_F",            __EVAL(ITEM_OTHER)},
			{"muzzle_snds_65_TI_ghex_F",           __EVAL(ITEM_OTHER)},
			{"muzzle_snds_65_TI_hex_F",            __EVAL(ITEM_OTHER)},
			{"muzzle_snds_93mmg",                  __EVAL(ITEM_OTHER)},
			{"muzzle_snds_93mmg_tan",              __EVAL(ITEM_OTHER)},
			{"muzzle_snds_B",                      __EVAL(ITEM_OTHER)},
			{"muzzle_snds_B_khk_F",                __EVAL(ITEM_OTHER)},
			{"muzzle_snds_B_snd_F",                __EVAL(ITEM_OTHER)},
			{"muzzle_snds_H",                      __EVAL(ITEM_OTHER)},
			{"muzzle_snds_H_MG",                   __EVAL(ITEM_OTHER)},
			{"muzzle_snds_H_MG_blk_F",             __EVAL(ITEM_OTHER)},
			{"muzzle_snds_H_MG_khk_F",             __EVAL(ITEM_OTHER)},
			{"muzzle_snds_H_khk_F",                __EVAL(ITEM_OTHER)},
			{"muzzle_snds_H_snd_F",                __EVAL(ITEM_OTHER)},
			{"muzzle_snds_L",                      __EVAL(ITEM_OTHER)},
			{"muzzle_snds_M",                      __EVAL(ITEM_OTHER)},
			{"muzzle_snds_acp",                    __EVAL(ITEM_OTHER)},
			{"muzzle_snds_m_khk_F",                __EVAL(ITEM_OTHER)},
			{"muzzle_snds_m_snd_F",                __EVAL(ITEM_OTHER)},
			{"optic_ACO_grn",                      __EVAL(ITEM_OTHER)},
			{"optic_ACO_grn_smg",                  __EVAL(ITEM_OTHER)},
			{"optic_AMS",                          __EVAL(ITEM_OTHER)},
			{"optic_AMS_khk",                      __EVAL(ITEM_OTHER)},
			{"optic_AMS_snd",                      __EVAL(ITEM_OTHER)},
			{"optic_Aco",                          __EVAL(ITEM_OTHER)},
			{"optic_Aco_smg",                      __EVAL(ITEM_OTHER)},
			{"optic_Arco",                         __EVAL(ITEM_OTHER)},
			{"optic_Arco_blk_F",                   __EVAL(ITEM_OTHER)},
			{"optic_Arco_ghex_F",                  __EVAL(ITEM_OTHER)},
			{"optic_DMS",                          __EVAL(ITEM_OTHER)},
			{"optic_DMS_ghex_F",                   __EVAL(ITEM_OTHER)},
			{"optic_ERCO_blk_F",                   __EVAL(ITEM_OTHER)},
			{"optic_ERCO_khk_F",                   __EVAL(ITEM_OTHER)},
			{"optic_ERCO_snd_F",                   __EVAL(ITEM_OTHER)},
			{"optic_Hamr",                         __EVAL(ITEM_OTHER)},
			{"optic_Hamr_khk_F",                   __EVAL(ITEM_OTHER)},
			{"optic_Holosight",                    __EVAL(ITEM_OTHER)},
			{"optic_Holosight_blk_F",              __EVAL(ITEM_OTHER)},
			{"optic_Holosight_khk_F",              __EVAL(ITEM_OTHER)},
			{"optic_Holosight_smg",                __EVAL(ITEM_OTHER)},
			{"optic_Holosight_smg_blk_F",          __EVAL(ITEM_OTHER)},
			{"optic_Holosight_smg_khk_F",          __EVAL(ITEM_OTHER)},
			{"optic_KHS_blk",                      __EVAL(ITEM_OTHER)},
			{"optic_KHS_hex",                      __EVAL(ITEM_OTHER)},
			{"optic_KHS_old",                      __EVAL(ITEM_OTHER)},
			{"optic_KHS_tan",                      __EVAL(ITEM_OTHER)},
			{"optic_LRPS",                         __EVAL(ITEM_OTHER)},
			{"optic_LRPS_ghex_F",                  __EVAL(ITEM_OTHER)},
			{"optic_LRPS_tna_F",                   __EVAL(ITEM_OTHER)},
			{"optic_MRCO",                         __EVAL(ITEM_OTHER)},
			{"optic_MRD",                          __EVAL(ITEM_OTHER)},
			{"optic_NVS",                          __EVAL(ITEM_OTHER)},
			{"optic_Nightstalker",                 __EVAL(ITEM_OTHER)},
			{"optic_PGO7_blk_F",                   __EVAL(ITEM_OTHER)},
			{"optic_SOS",                          __EVAL(ITEM_OTHER)},
			{"optic_SOS_khk_F",                    __EVAL(ITEM_OTHER)},
			{"optic_Yorris",                       __EVAL(ITEM_OTHER)},
			{"optic_tws",                          __EVAL(ITEM_OTHER)},
			{"optic_tws_mg",                       __EVAL(ITEM_OTHER)},
			{"tf_anprc152",                        __EVAL(ITEM_OTHER)}, // Better
			{"tf_microdagr",                       __EVAL(ITEM_OTHER)},
			{"tf_rf7800str",                       __EVAL(ITEM_OTHER)}  // Cheapo shortrange
		};
	};
};